spring:
  application:
    name: saliai_wechat
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@120.76.152.81:1521:saliai
    username:
    password:
    initial-size: 5                 # 初始化连接数
    min-idle: 1                     # 最小连接数
    max-active: 20                  # 最大连接数
    max-wait: 600000                # 获取连接等待超时的时间
    removeAbandoned: true           # 超过时间限制是否回收
    removeAbandonedTimeout: 20000   # 超过时间限制多长
    time-between-eviction-runs-millis: 600000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    min-evictable-idle-time-millis: 300000  # 配置一个连接在池中最小生存的时间，单位是毫秒
    validation-query: select 'x'  # 用来检测连接是否有效的sql，要求是一个查询语句
    test-while-idle: true         # 申请连接的时候检测
    test-on-borrow: false         # 申请连接时执行validationQuery检测连接是否有效，配置为true会降低性能
    test-on-return: false         # 归还连接时执行validationQuery检测连接是否有效，配置为true会降低性能
    # 打开PSCache，并且指定每个连接上PSCache的大小
    pool-prepared-statements: true
    max-pool-prepared-statement-per-connection-size: 50
    # 监控统计用的filter:stat 日志用的filter:log4j 防御SQL注入的filter:wall
    filters: stat,wall,log4j,config
  jackson:
    serialization:
      #格式化输出
      indent_output: true
      #忽略无法转换的对象
      fail_on_empty_beans: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: localhost
    port: 6379
    password: 123456

## 端口
server:
  port: 8083
  servlet:
   context-path: /saliai_wechat

## Mybatis
mybatis:
  type-aliases-package: com.saliai.medical_beauty.dto
  mapper-locations: classpath:com/saliai/wechat/mapper/*.xml
  config-location: classpath:mybatis-config.xml

## 日志
logging:
  config: classpath:logback-spring.xml